apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: canary-backend
  namespace: default

spec:
  replicas: 4

  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 20s

        - setWeight: 50
        - pause:
            duration: 20s

  selector:
    matchLabels:
      app: canary-backend

  template:
    metadata:
      labels:
        app: canary-backend

    spec:
      containers:
        - name: poc-canary-backend
          newTag: "36"
          imagePullPolicy: Never

          ports:
            - containerPort: 3000
